# Generated by Django 3.2.5 on 2024-02-26 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=250)),
                ('model_description', models.TextField(default='')),
                ('model_details', models.TextField(default='')),
                ('model_gender', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('display_image', models.URLField()),
                ('delivery_cost', models.FloatField(default=0.0, null=True)),
                ('slug', models.SlugField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2024, 2, 26, 12, 38, 49, 712667, tzinfo=utc))),
            ],
        ),
    ]
