# Generated by Django 3.2.5 on 2024-04-01 22:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 22, 15, 8, 281457, tzinfo=utc)),
        ),
    ]
