# Generated by Django 3.2.5 on 2024-02-26 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_models_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 19, 46, 16, 911684, tzinfo=utc)),
        ),
    ]
