# Generated by Django 3.2.5 on 2024-04-26 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_models_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 12, 17, 24, 157613, tzinfo=utc)),
        ),
    ]
