# Generated by Django 3.2.5 on 2024-03-23 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_models_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 16, 14, 43, 602543, tzinfo=utc)),
        ),
    ]
