# Generated by Django 3.2.5 on 2023-12-15 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 13, 26, 37, 202112, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='sizes',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
