# Generated by Django 3.2.5 on 2023-11-05 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddashboard',
            name='items',
            field=models.ManyToManyField(to='brands.Merchandise'),
        ),
        migrations.AddField(
            model_name='branddashboard',
            name='total_orders',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 20, 52, 28, 439912, tzinfo=utc)),
        ),
    ]
