# Generated by Django 3.2.5 on 2024-04-26 12:17

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='available_colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='available_sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 12, 17, 24, 146597, tzinfo=utc)),
        ),
    ]
