# Generated by Django 3.2.5 on 2023-11-24 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20231123_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 9, 54, 57, 672649, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='merchandise_type',
            field=models.CharField(blank=True, choices=[('Tops', 'Tops'), ('Pants', 'Pants'), ('Sweaters', 'Sweaters'), ('T-Shirts', 'T-Shirts'), ('Jackets', 'Jackets'), ('Denim', 'Denim'), ('Watches', 'Watches'), ('Wallets', 'Wallets'), ('Bags', 'Bags'), ('Sunglasses', 'Sunglasses'), ('Hats and Caps', 'Hats and Caps'), ('Belts', 'Belts'), ('Shoes ', 'Shoes'), ('Slides ', 'Slides'), ('Bracelets ', 'Bracelets'), ('Pendants ', 'Pendants'), ('Sweatshirts', 'Sweatshirts'), ('Hoodies', 'Hoodies'), ('Masks', 'Masks'), ('Lumberjacks & Vintage', 'Lumberjacks and Vintage'), ('Piercings & Studs', 'Piercings & Studs'), ('Baggy Wears', 'Baggy Wears'), ('Tattoos', 'Tattoos'), ('Chains & Necklaces', 'Chains & Necklaces'), ('Vintage Shirts', 'Vintage Shirts'), ('Native Wears', 'Native Wears'), ('Watches', 'Watches'), ('Wallets', 'Wallets'), ('Bags', 'Bags'), ('Sunglasses', 'Sunglasses'), ('Hats and Caps', 'Hats and Caps'), ('Belts', 'Belts'), ('Skating', 'Skating'), ('Hoodies', 'Hoodies'), ('Baggy Wears', 'Baggy Wears'), ('Rings', 'Rings'), ('Earrings', 'Earrings'), ('Joggers', 'Joggers'), ('Jeans', 'Jeans')], default='', max_length=250, null=True),
        ),
    ]
