# Generated by Django 3.2.5 on 2023-11-07 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='category',
            field=models.CharField(blank=True, choices=[('Choose your desired collection', 'Choose your desired collection'), ('Tees', 'Tees'), ('Rings', 'Rings'), ('Joggers', 'Joggers'), ('Chains & Necklaces', 'Chains & Necklaces'), ('Jeans', 'Jeans'), ('Jackets', 'Jackets'), ('Skating', 'Skating'), ('Caps and Hats', 'Caps and Hats'), ('Skating', 'Skating'), ('Sweatshirts', 'Sweatshirts'), ('Hoodies', 'Hoodies'), ('Kicks & Slides', 'Kicks & Slides'), ('Masks', 'Masks'), ('Shades', 'Shades'), ('Lumberjacks & Vintage', 'Lumberjacks and Vintage'), ('Piercings & Studs', 'Piercings & Studs'), ('Baggy Wears', 'Baggy Wears'), ('Tattoos', 'Tattoos'), ('Graffiti', 'Graffiti')], default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 17, 21, 5, 88088, tzinfo=utc)),
        ),
    ]
