# Generated by Django 3.2.5 on 2023-12-15 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_auto_20231215_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 13, 34, 3, 623464, tzinfo=utc)),
        ),
    ]
