# Generated by Django 3.2.5 on 2024-02-26 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='aesthetics',
            name='aesthetic_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 12, 54, 57, 474027, tzinfo=utc)),
        ),
    ]
