# Generated by Django 3.2.5 on 2023-12-18 10:36

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_auto_20231215_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='available_sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 10, 36, 5, 589831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='merchandise_type',
            field=models.CharField(blank=True, choices=[('Tops', 'Tops'), ('Pants', 'Pants'), ('Sweaters', 'Sweaters'), ('T-Shirts', 'T-Shirts'), ('Jackets', 'Jackets'), ('Denim', 'Denim'), ('Watches', 'Watches'), ('Wallets', 'Wallets'), ('Bags', 'Bags'), ('Sunglasses', 'Sunglasses'), ('Hats and Caps', 'Hats and Caps'), ('Belts', 'Belts'), ('Shoes ', 'Shoes'), ('Slides ', 'Slides'), ('Bracelets ', 'Bracelets'), ('Pendants ', 'Pendants'), ('Sweatshirts', 'Sweatshirts'), ('Hoodies', 'Hoodies'), ('Masks', 'Masks'), ('Lumberjacks', 'Lumberjacks'), ('Piercings & Studs', 'Piercings & Studs'), ('Baggy Wears', 'Baggy Wears'), ('Tattoos', 'Tattoos'), ('Chains & Necklaces', 'Chains & Necklaces'), ('Vintage Shirts', 'Vintage Shirts'), ('Native Wears', 'Native Wears'), ('Watches', 'Watches'), ('Wallets', 'Wallets'), ('Bags', 'Bags'), ('Sunglasses', 'Sunglasses'), ('Hats & Caps', 'Hats & Caps'), ('Belts', 'Belts'), ('Skating', 'Skating'), ('Hoodies', 'Hoodies'), ('Baggy Wears', 'Baggy Wears'), ('Rings', 'Rings'), ('Earrings', 'Earrings'), ('Joggers', 'Joggers'), ('Jeans', 'Jeans')], default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='size_type',
            field=models.CharField(blank=True, choices=[('', ''), ('Clothing Size', 'Clothing Size'), ('Ring Size', 'Ring Size'), ('Foot Size', 'Foot Size'), ('Wrist Size', 'Wrist Size'), ('Neck Size', 'Neck Size')], default='', max_length=250, null=True),
        ),
    ]
