# Generated by Django 3.2.5 on 2023-11-20 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='merchandise_gender',
            field=models.CharField(blank=True, choices=[('M', 'Men'), ('W', 'Women'), ('NB', 'Non-Binary')], default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 19, 28, 26, 746555, tzinfo=utc)),
        ),
    ]
