# Generated by Django 3.2.5 on 2024-02-26 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_auto_20240226_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 19, 46, 16, 903615, tzinfo=utc)),
        ),
    ]
