# Generated by Django 3.2.5 on 2023-12-22 06:37

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_auto_20231218_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='available_color_1',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='available_color_2',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='available_color_3',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='available_colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 6, 36, 55, 927374, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='size_type',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('clothing ', 'clothing '), ('rings ', 'rings '), ('foot ', 'foot '), ('wrist ', 'wrist '), ('neck ', 'neck ')], default='', max_length=250, null=True),
        ),
    ]
