# Generated by Django 3.2.5 on 2023-12-22 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_auto_20231222_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 17, 2, 43, 809463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='display_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='merchandise_type',
            field=models.CharField(blank=True, choices=[('Tops', 'Tops'), ('Pants', 'Pants'), ('Sweaters', 'Sweaters'), ('T-Shirts', 'T-Shirts'), ('Jackets', 'Jackets'), ('Denim', 'Denim'), ('Watches', 'Watches'), ('Wallets', 'Wallets'), ('Bags', 'Bags'), ('Sunglasses', 'Sunglasses'), ('Hats and Caps', 'Hats and Caps'), ('Belts', 'Belts'), ('Shoes ', 'Shoes'), ('Slides ', 'Slides'), ('Bracelets ', 'Bracelets'), ('Pendants ', 'Pendants'), ('Sweatshirts', 'Sweatshirts'), ('Hoodies', 'Hoodies'), ('Masks', 'Masks'), ('Lumberjacks', 'Lumberjacks'), ('Piercings & Studs', 'Piercings & Studs'), ('Baggy Wears', 'Baggy Wears'), ('Tattoos', 'Tattoos'), ('Chains & Necklaces', 'Chains & Necklaces'), ('Vintage Shirts', 'Vintage Shirts'), ('Native Wears', 'Native Wears'), ('Watches', 'Watches'), ('Wallets', 'Wallets'), ('Bags', 'Bags'), ('Sunglasses', 'Sunglasses'), ('Hats & Caps', 'Hats & Caps'), ('Belts', 'Belts'), ('Skating', 'Skating'), ('Hoodies', 'Hoodies'), ('Baggy Wears', 'Baggy Wears'), ('Rings', 'Rings'), ('Earrings', 'Earrings'), ('Joggers', 'Joggers'), ('Jeans', 'Jeans')], default='None', max_length=250, null=True),
        ),
    ]
