# Generated by Django 3.2.5 on 2024-03-20 15:20

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0008_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='WishList',
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 15, 20, 3, 817391, tzinfo=utc)),
        ),
    ]
