# Generated by Django 3.2.5 on 2023-12-23 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_auto_20231222_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 8, 7, 17, 684522, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='size_type',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
