# Generated by Django 3.2.5 on 2024-03-20 18:34

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_auto_20240320_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='available_colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='available_sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='delivery_cost',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='discount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='display_image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='image_1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Merch Image'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='image_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Merch Image'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='image_3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Merch Image'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='image_4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Merch Image'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='image_5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Merch Image'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='labels',
            field=models.CharField(choices=[('None', 'None'), ('New Merchandise', 'New Merchandise'), ('Limited Stock', 'Limited Stock'), ('FREE DELIVERY', 'FREE DELIVERY')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='merchandise_color',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='merchandise_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='merchandise_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='merchandise_gender',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='merchandise_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='merchandise_type',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='size_type',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 18, 34, 3, 61002, tzinfo=utc)),
        ),
    ]
