# Generated by Django 3.2.5 on 2023-11-29 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_auto_20231127_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 13, 22, 11, 901360, tzinfo=utc)),
        ),
    ]
