# Generated by Django 3.2.5 on 2023-12-23 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_auto_20231223_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 9, 5, 14, 176574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='merchandise_gender',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='merchandise_type',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
