# Generated by Django 3.2.5 on 2023-12-05 05:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0011_auto_20231203_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, default='', null=True, to='brands.MerchandiseAvailableSizes'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 5, 41, 34, 352291, tzinfo=utc)),
        ),
    ]
