# Generated by Django 3.2.5 on 2023-12-05 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0013_auto_20231205_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='category',
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 5, 54, 22, 477556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='delivery_cost',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='discount',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
