# Generated by Django 3.2.5 on 2023-12-05 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0026_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandiseavailablesizes',
            name='merchandise_name',
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 10, 52, 13, 421819, tzinfo=utc)),
        ),
    ]
