# Generated by Django 3.2.5 on 2023-11-24 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231123_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 9, 54, 57, 688291, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='branduser',
            name='brand_logo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='branduser',
            name='user_type',
            field=models.CharField(choices=[('brand', 'brand')], default='brand', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 9, 54, 57, 688291, tzinfo=utc)),
        ),
    ]
