# Generated by Django 3.2.5 on 2024-04-26 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240426_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 12, 10, 19, 708373, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='branduser',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 12, 10, 19, 706377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 12, 10, 19, 707375, tzinfo=utc)),
        ),
    ]
