# Generated by Django 3.2.5 on 2024-02-26 19:46

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20240226_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='branduser',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 19, 46, 16, 911684, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 19, 46, 16, 911684, tzinfo=utc)),
        ),
    ]
