# Generated by Django 3.2.5 on 2023-11-07 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20231106_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 17, 21, 5, 98573, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='branduser',
            name='brand_type',
            field=models.CharField(choices=[('Clothing & Apparel', 'Clothing and Apparel'), ('Accessories', 'Accessories'), ('Arts', 'Arts'), ('Footwears & Canvas', 'Footwears & Canvas')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 17, 21, 5, 97533, tzinfo=utc)),
        ),
    ]
