# Generated by Django 3.2.5 on 2023-11-17 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20231107_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 17, 47, 54, 917077, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='branduser',
            name='brand_type',
            field=models.CharField(choices=[('Clothing & Apparel', 'Clothing and Apparel'), ('Accessories', 'Accessories'), ('Arts', 'Arts'), ('Footwears & Canvas', 'Footwears & Canvas'), ('Enigmas', 'Enigmas'), ('Watches', 'Wristwatches & Handbands'), ('Skates', 'Skates'), ('Cap', 'Cap'), ('Masks', 'Masks')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 17, 47, 54, 917077, tzinfo=utc)),
        ),
    ]
