# Generated by Django 3.2.5 on 2024-03-08 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240228_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='branduser',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 10, 48, 49, 563360, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 10, 48, 49, 564358, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 10, 48, 49, 563360, tzinfo=utc)),
        ),
    ]
