# Generated by Django 3.2.5 on 2023-12-05 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20231205_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 6, 39, 22, 812460, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 6, 39, 22, 812460, tzinfo=utc)),
        ),
    ]
