# Generated by Django 3.2.5 on 2024-04-01 22:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 22, 14, 18, 235354, tzinfo=utc)),
        ),
    ]
