# Generated by Django 3.2.5 on 2024-04-01 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(blank=True, max_length=250)),
                ('user_email', models.CharField(blank=True, max_length=250)),
                ('name_of_brand', models.CharField(blank=True, max_length=250)),
                ('amount_per_item', models.CharField(blank=True, max_length=250)),
                ('quantity', models.CharField(blank=True, max_length=250)),
                ('tracking_number', models.CharField(default='BHCSo3RXRN2J', max_length=250)),
                ('number_of_items', models.IntegerField(null=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('ordered', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2024, 4, 1, 22, 11, 49, 955890, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=250)),
                ('full_name', models.CharField(blank=True, max_length=250)),
                ('paystack_charge_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('C', 'Completed')], max_length=250, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.order')),
            ],
        ),
    ]
