# Generated by Django 3.2.5 on 2023-12-05 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_auto_20231205_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='6b1691fd033b46299f47d277005fd170', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 6, 44, 22, 892425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='545epHChweE7', max_length=250),
        ),
    ]
