# Generated by Django 3.2.5 on 2023-12-05 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20231205_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='t3Qo0tPwv25R', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='42461dd8b95045999f8542031491737b', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 6, 50, 21, 650931, tzinfo=utc)),
        ),
    ]
