# Generated by Django 3.2.5 on 2023-12-05 07:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20231205_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='dea0f88b5c4b4312b2ef1d9b5b15c49f', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 7, 8, 23, 346678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='vNQE4CcLQD9P', max_length=250),
        ),
    ]
