# Generated by Django 3.2.5 on 2023-12-05 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_auto_20231205_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paystack_charge_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='074fa071395e4771bb57ba538004f46b', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 10, 52, 13, 428805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='aDfQVV4j59iz', max_length=250),
        ),
    ]
