# Generated by Django 3.2.5 on 2024-04-22 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 11, 7, 35, 661563, tzinfo=utc)),
        ),
    ]
