# Generated by Django 3.2.5 on 2024-02-26 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 12, 38, 49, 716668, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
