# Generated by Django 3.2.5 on 2024-04-01 22:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 22, 15, 39, 790395, tzinfo=utc)),
        ),
    ]
