# Generated by Django 3.2.5 on 2024-04-26 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_reviews_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 12, 10, 19, 715252, tzinfo=utc)),
        ),
    ]
