# Generated by Django 3.2.5 on 2024-03-08 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_reviews_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 10, 48, 49, 569813, tzinfo=utc)),
        ),
    ]
