# Generated by Django 3.2.5 on 2024-03-23 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=250, null=True)),
                ('product_description', models.TextField(default='')),
                ('display_image', models.URLField()),
                ('highest_bid', models.CharField(blank=True, max_length=250, null=True)),
                ('current_bid', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2024, 3, 23, 16, 14, 43, 529959, tzinfo=utc))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2024, 3, 23, 16, 14, 43, 529959, tzinfo=utc))),
            ],
        ),
    ]
