# Generated by Django 3.2.5 on 2024-02-26 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 12, 38, 49, 696328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 12, 38, 49, 696328, tzinfo=utc)),
        ),
    ]
