# Generated by Django 3.2.5 on 2024-02-28 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20240226_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 13, 52, 58, 200376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 13, 52, 58, 200376, tzinfo=utc)),
        ),
    ]
